### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Takabrycheri** [loadsmileau/native_updater#37]
/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-2.0.0/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (226, 26): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

**Comment by vixez** [comment]
Same here

**Comment by vixez** [comment]
`in_app_update` dependency needed to be updated.

Can use this temporarily:
```
  native_updater:
    git:
      url: https://github.com/vixez/native_updater.git
      ref: master
```

PR: https://github.com/ofload/native_updater/pull/38

And if you use `in_app_review` check this: https://github.com/britannio/in_app_review/issues/78#issuecomment-1332243210
